### PR TITLE
Updates dependency to Spree 3.4.5

### PR DESCRIPTION
**Pull request by poudelprakash**
1. updates spree dependecny
2. self.preferred_fee was nil and there was error, that prevented checkout using COD method, fee_exists? method updated to check this
3. Solves typo in generator

### CODE REVIEW

**Comment by poudelprakash** [comment]
@sylvinho81 Could you look into this PR, this would make this gem usable with latest version of spree.

I am not sure if I did it right updating `fee_exists?` method, but there was problem while saving adjustment because self.preferred_fee was `nil`. This was preventing me moving past payment stage in checkout

**Comment by sylvinho81** [comment]
@poudelprakash, I was wondering if we should assign a default value...

preference :fee, :float,  :default => 0.0

Thanks for being on top of this.

**Comment by poudelprakash** [comment]
@sylvinho81 yes, that works too, updated code and squashed commits.
Ready to merge

**Comment by sylvinho81** [comment]
@poudelprakash just one thing. you want to merge it into 3-0-stable.  Maybe we should create a new branch 3-4-stable. no?

**Comment by poudelprakash** [comment]
@sylvinho81 yes, that's great idea but you are the owner of this repo and only you have permissions to create new branch,
let me know when you have created a new branch and I will edit pull request

**Comment by sylvinho81** [comment]
@poudelprakash I already created that branch.

**Comment by poudelprakash** [comment]
@sylvinho81 updated pull request, should I also do version bump? maybe to 3.1.0?

**Comment by sylvinho81** [comment]
@poudelprakash feel free to do it. Let me know and I can merge the pull request. Thanks!

**Comment by poudelprakash** [comment]
@sylvinho81 done

**Pull request merged**
